In [1]:
import torch

In [2]:
print(torch.__version__)

1.12.0+cu113


In [4]:
torch.cuda.is_available()

True

Tensors and operations

In [5]:
import torch
import numpy
import os

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [9]:
basic_tensor = torch.tensor([[1,2,3],[4,5,6]])
basic_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
basic_tensor.dtype

torch.int64

In [12]:
basic_tensor.device

device(type='cpu')

In [13]:
basic_tensor.shape

torch.Size([2, 3])

Below line means, In back propagartion wil we requires gradients or not.

In [15]:
basic_tensor.requires_grad

False

In [20]:
tensor = torch.tensor([[1,2,3],[11,22,33]],
                     dtype=torch.float,
                     device=device,
                     requires_grad=True)

tensor

tensor([[ 1.,  2.,  3.],
        [11., 22., 33.]], device='cuda:0', requires_grad=True)

In [21]:
tensor.requires_grad

True

In [22]:
tensor.shape

torch.Size([2, 3])

In [23]:
tensor.device

device(type='cuda', index=0)

### Other commonly used tensors

In [24]:
x = torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
x = torch.zeros(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
x = torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
x = torch.rand(size=(3,4))
x

tensor([[0.7982, 0.1910, 0.0704, 0.2870],
        [0.8078, 0.0009, 0.5064, 0.4672],
        [0.1896, 0.4587, 0.8534, 0.0707]])

In [30]:
#creating indentity matrix whichi s creatred inthe form mof square
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [31]:
x = torch.arange(start=0, end=7, step=2)
x

tensor([0, 2, 4, 6])

In [32]:
x = torch.linspace(start=0, end=7, steps=10)
x

tensor([0.0000, 0.7778, 1.5556, 2.3333, 3.1111, 3.8889, 4.6667, 5.4444, 6.2222,
        7.0000])

In [33]:
x = torch.rand(size=(3,4)).normal_(mean=0, std=1)
x

tensor([[ 0.9630,  0.3905,  0.0860, -0.3610],
        [-1.0086, -0.0504,  0.9334, -0.2009],
        [ 0.5388, -1.2703,  0.1546, -0.9223]])

In [35]:
#check for values with uniform distribution
x = torch.rand(size=(3,4)).uniform_(3, 6)
x

tensor([[4.0852, 3.1710, 3.9816, 5.3849],
        [3.3237, 5.4260, 5.9643, 3.3965],
        [3.3192, 5.5662, 3.2857, 5.9662]])

In [36]:
#creating diagonal matrix
x = torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
x = torch.diag(5*torch.ones(10))
x

tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

Conversion

In [38]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [39]:
x.bool()

tensor([False,  True,  True,  True])

In [40]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [41]:
x.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [42]:
x.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [44]:
x.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [46]:
import numpy as np
np_array = np.array([[1,2,3], [1,2,3]])

np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [47]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [48]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])

Mathematical operations

In [49]:
import numpy as np
import os
import torch

In [50]:
x = torch.arange(start=10, end=20, step=4)
y = torch.arange(start=5, end=15, step=4)

x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [51]:
x

tensor([10, 14, 18])

In [52]:
y

tensor([ 5,  9, 13])

In [53]:
x+y

tensor([15, 23, 31])

In [54]:
x-y

tensor([5, 5, 5])

In [57]:
#Element wise multilication

x*y

tensor([ 50, 126, 234])

In [56]:
x/y

tensor([2.0000, 1.5556, 1.3846])

In [73]:
#sum of element wise multiplication
torch.dot(x, y)

tensor(410)

In [59]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [60]:
z+=x
z

tensor([11., 15., 19.])

In [61]:
## inplace addition
z.add_(x)
z

tensor([21., 29., 37.])

Above Z value itself is changed as per the calculation done

In [62]:
x.pow(2)

tensor([100, 196, 324])

In [63]:
x**2

tensor([100, 196, 324])

In [65]:
x > 100

tensor([False, False, False])

In [67]:
# Matrix multpltplication
#column of first matrix shuold be equal to row of second matrix
A = torch.rand(size=(3,5))
B = torch.rand(size=(5,4))

A @ B 

tensor([[0.7008, 0.3587, 0.4940, 0.6589],
        [1.4095, 1.3885, 0.9618, 1.0781],
        [1.8580, 1.6633, 1.8015, 1.7129]])

In [69]:
#alternative of matrix multiplication
A.matmul(B)

tensor([[0.7008, 0.3587, 0.4940, 0.6589],
        [1.4095, 1.3885, 0.9618, 1.0781],
        [1.8580, 1.6633, 1.8015, 1.7129]])

In [70]:
X = torch.rand((3,3))
X.matrix_exp()

tensor([[1.7013, 1.5318, 1.3006],
        [0.9768, 2.3918, 0.9508],
        [1.0583, 1.1044, 1.6020]])

In [71]:
X.matrix_power(2)

tensor([[0.9660, 0.8507, 0.3610],
        [0.5838, 0.9043, 0.6581],
        [0.2452, 0.8309, 0.7853]])

In [74]:
# Broadcasting

A

tensor([[0.1035, 0.2108, 0.0949, 0.1781, 0.6321],
        [0.2418, 0.5210, 0.9309, 0.0022, 0.4462],
        [0.5907, 0.5954, 0.8687, 0.4809, 0.9276]])

In [75]:
A + 1

tensor([[1.1035, 1.2108, 1.0949, 1.1781, 1.6321],
        [1.2418, 1.5210, 1.9309, 1.0022, 1.4462],
        [1.5907, 1.5954, 1.8687, 1.4809, 1.9276]])

In [76]:
A * 5

tensor([[0.5174, 1.0538, 0.4746, 0.8903, 3.1604],
        [1.2090, 2.6048, 4.6546, 0.0112, 2.2309],
        [2.9534, 2.9771, 4.3434, 2.4046, 4.6381]])

In [77]:
A.shape

torch.Size([3, 5])

In [78]:
C = torch.ones((1,5))
C

tensor([[1., 1., 1., 1., 1.]])

In [79]:
A - C

tensor([[-0.8965, -0.7892, -0.9051, -0.8219, -0.3679],
        [-0.7582, -0.4790, -0.0691, -0.9978, -0.5538],
        [-0.4093, -0.4046, -0.1313, -0.5191, -0.0724]])

In [80]:
A + C

tensor([[1.1035, 1.2108, 1.0949, 1.1781, 1.6321],
        [1.2418, 1.5210, 1.9309, 1.0022, 1.4462],
        [1.5907, 1.5954, 1.8687, 1.4809, 1.9276]])

In [81]:
D = torch.ones((3, 1))
D

tensor([[1.],
        [1.],
        [1.]])

In [82]:
A - D

tensor([[-0.8965, -0.7892, -0.9051, -0.8219, -0.3679],
        [-0.7582, -0.4790, -0.0691, -0.9978, -0.5538],
        [-0.4093, -0.4046, -0.1313, -0.5191, -0.0724]])

In [83]:
A + D

tensor([[1.1035, 1.2108, 1.0949, 1.1781, 1.6321],
        [1.2418, 1.5210, 1.9309, 1.0022, 1.4462],
        [1.5907, 1.5954, 1.8687, 1.4809, 1.9276]])

In [84]:
torch.sum(D)

tensor(3.)

In [85]:
torch.sum(A)

tensor(6.8247)

In [86]:
A

tensor([[0.1035, 0.2108, 0.0949, 0.1781, 0.6321],
        [0.2418, 0.5210, 0.9309, 0.0022, 0.4462],
        [0.5907, 0.5954, 0.8687, 0.4809, 0.9276]])

In [87]:
torch.max(A)

tensor(0.9309)

In [88]:
torch.min(A)

tensor(0.0022)

In [89]:
torch.min(A, dim=1)

torch.return_types.min(
values=tensor([0.0949, 0.0022, 0.4809]),
indices=tensor([2, 3, 3]))

In [90]:
torch.max(A, dim=1) # row wise max 

torch.return_types.max(
values=tensor([0.6321, 0.9309, 0.9276]),
indices=tensor([4, 2, 4]))

In [91]:
torch.max(A, dim=0) # col wise max

torch.return_types.max(
values=tensor([0.5907, 0.5954, 0.9309, 0.4809, 0.9276]),
indices=tensor([2, 2, 1, 2, 2]))

In [92]:
torch.abs(-A)

tensor([[0.1035, 0.2108, 0.0949, 0.1781, 0.6321],
        [0.2418, 0.5210, 0.9309, 0.0022, 0.4462],
        [0.5907, 0.5954, 0.8687, 0.4809, 0.9276]])

In [93]:
A

tensor([[0.1035, 0.2108, 0.0949, 0.1781, 0.6321],
        [0.2418, 0.5210, 0.9309, 0.0022, 0.4462],
        [0.5907, 0.5954, 0.8687, 0.4809, 0.9276]])

In [94]:
torch.argmax(A)

tensor(7)

In [95]:
torch.argmax(A, dim=1) # row wise argmax

tensor([4, 2, 4])

In [96]:
torch.argmax(A, dim=0) # col wise argmax

tensor([2, 2, 1, 2, 2])

In [97]:
torch.argmin(A)

tensor(8)

In [98]:
torch.mean(A)

tensor(0.4550)

In [99]:
torch.mean(A, dim=1) # row wise mean

tensor([0.2439, 0.4284, 0.6927])

In [100]:
torch.mean(A, dim=0) # col wise mean

tensor([0.3120, 0.4424, 0.6315, 0.2204, 0.6686])

In [101]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [102]:
torch.eq(A, D)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [103]:
torch.eq(D, D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [104]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.0949, 0.1035, 0.1781, 0.2108, 0.6321],
        [0.0022, 0.2418, 0.4462, 0.5210, 0.9309],
        [0.4809, 0.5907, 0.5954, 0.8687, 0.9276]]),
indices=tensor([[2, 0, 3, 1, 4],
        [3, 0, 4, 1, 2],
        [3, 0, 1, 2, 4]]))

Any Values below 0.5 will represent as 0.5 this is clamping operation

In [105]:
torch.clamp(A, min=0.5)

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.6321],
        [0.5000, 0.5210, 0.9309, 0.5000, 0.5000],
        [0.5907, 0.5954, 0.8687, 0.5000, 0.9276]])